
echo "[build]
builder = \"nixpacks\"
buildCommand = \"yarn build\"

[deploy]
startCommand = \"yarn start\"
healthcheckPath = \"/\"
healthcheckTimeout = 100

[database]
type = \"sqlite\"" > railway.toml
